# ═══════════════════════════════════════════════════════════════════════════
# ANDA APP — ProGuard / R8 Configuration
# Last updated: Sprint 2 — Security hardening (LGPD / Lei 13.709/2018)
#
# Sections:
#   1.  Debug info & stack traces
#   2.  Kotlin core
#   3.  Kotlin coroutines
#   4.  Room (entities, DAOs, migrations)
#   5.  Security — AES-GCM encryption & Android KeyStore
#   6.  Firebase Authentication
#   7.  AndroidX Credentials / Google Identity
#   8.  ViewBinding
#   9.  WorkManager workers
#   10. Activities & Application
#   11. CameraX / ML Kit
#   12. Enum classes
#   13. Serialisation safety
# ═══════════════════════════════════════════════════════════════════════════


# ── 1. Debug info & stack traces ─────────────────────────────────────────────
# Keep file names and line numbers so crash reports are readable.
# -renamesourcefileattribute replaces the real file name in release builds while
# -keepattributes SourceFile preserves the attribute for mapping tools.
-keepattributes SourceFile,LineNumberTable,*Annotation*,Signature,InnerClasses,EnclosingMethod
-renamesourcefileattribute SourceFile


# ── 2. Kotlin core ────────────────────────────────────────────────────────────
# Kotlin reflection metadata — needed for data-class `copy()`, companion objects,
# default parameter values, and any code that reads @JvmStatic / @JvmField at runtime.
-keep class kotlin.Metadata { *; }
-keepclassmembers class ** {
    @kotlin.jvm.JvmStatic <methods>;
    @kotlin.jvm.JvmField  <fields>;
}
-dontwarn kotlin.**


# ── 3. Kotlin coroutines ──────────────────────────────────────────────────────
# Required so coroutine stack traces include the suspension point.
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-keepclassmembernames class kotlinx.coroutines.** { volatile <fields>; }
-dontwarn kotlinx.coroutines.**


# ── 4. Room (entities, DAOs, migrations) ──────────────────────────────────────
# Room uses reflection to locate and instantiate DAOs and entities; renaming or
# removing them will silently corrupt the database at runtime.
-keep class androidx.room.RoomDatabase { *; }
-keep class com.example.anda.data.local.** { *; }          # entities + DAOs + migrations
-keep @androidx.room.Entity class * { *; }
-keep @androidx.room.Dao    class * { *; }
# Keep the abstract DAO factory methods generated by Room's KSP processor.
-keepclassmembers class * extends androidx.room.RoomDatabase {
    abstract !static <methods>;
}


# ── 5. Security — AES-GCM encryption & Android KeyStore ──────────────────────
# These classes are called via normal dispatch (not reflection), but R8 could
# inline / remove intermediate helpers.  Keep the full surface so that:
#   • EncryptionException carries its class name in crash reports;
#   • AesGcmFieldEncryptor key-alias constant survives shrinking;
#   • LocalDataProtection PREFIX constant is not inlined away (it is compared
#     at runtime via startsWith).
-keep class com.example.anda.data.security.** { *; }
-keep class com.example.anda.core.security.**  { *; }

# Preserve EncryptionException so catch blocks survive obfuscation.
-keep class com.example.anda.data.security.EncryptionException { *; }


# ── 6. Firebase Authentication ────────────────────────────────────────────────
# Firebase SDK ships its own consumer ProGuard rules inside the AAR.  We add
# targeted guards for the specific public API surface used by the app.
-keep class com.google.firebase.auth.FirebaseAuth        { *; }
-keep class com.google.firebase.auth.FirebaseUser        { *; }
-keep class com.google.firebase.auth.AuthResult          { *; }
-keep class com.google.firebase.auth.GoogleAuthProvider  { *; }
-dontwarn com.google.firebase.**


# ── 7. AndroidX Credentials / Google Identity ────────────────────────────────
# Keep only the classes directly referenced by SignInActivity / CredentialManager calls.
-keep class androidx.credentials.CredentialManager            { *; }
-keep class androidx.credentials.GetCredentialRequest         { *; }
-keep class androidx.credentials.GetCredentialResponse        { *; }
-keep class androidx.credentials.CustomCredential             { *; }
-keep class androidx.credentials.exceptions.GetCredentialException { *; }
-keep class com.google.android.libraries.identity.googleid.GetGoogleIdOption   { *; }
-keep class com.google.android.libraries.identity.googleid.GoogleIdTokenCredential { *; }
-dontwarn androidx.credentials.**
-dontwarn com.google.android.libraries.identity.**


# ── 8. ViewBinding ────────────────────────────────────────────────────────────
-keep class com.example.anda.databinding.** { *; }


# ── 9. WorkManager workers ────────────────────────────────────────────────────
-keep class com.example.anda.** extends androidx.work.ListenableWorker { *; }
# WorkManager instantiates workers via a two-arg constructor.
-keepclassmembers class * extends androidx.work.Worker {
    public <init>(android.content.Context, androidx.work.WorkerParameters);
}


# ── 10. Activities & Application ─────────────────────────────────────────────
-keep class com.example.anda.** extends android.app.Activity    { *; }
-keep class com.example.anda.** extends android.app.Application { *; }


# ── 11. CameraX / ML Kit ─────────────────────────────────────────────────────
# These SDKs use SPI loading and internal reflection; suppress R8 warnings.
-dontwarn androidx.camera.**
-dontwarn com.google.mlkit.**


# ── 12. Enum classes ─────────────────────────────────────────────────────────
# Preserve values() and valueOf() — used by Room, JSON serialisers, and switch
# expressions on enums derived from network responses.
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}


# ── 13. Serialisation safety ─────────────────────────────────────────────────
# Preserve Serializable / Parcelable implementors (used by Intent extras and
# some AndroidX APIs).
-keepclassmembers class * implements java.io.Serializable {
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
-keepclassmembers class * implements android.os.Parcelable {
    public static final android.os.Parcelable$Creator CREATOR;
}
